### ISSUE TITLE
create_layer contains wrong indentation preventing creation of multi-sampled layer

### ISSUE THREAD

**Issue by yaqwsx** [fookatchu/pyphotonfile#10]
[This line](https://github.com/fookatchu/pyphotonfile/blob/e73e6fad11185cb6a08a6c6d29db92b786d17680/pyphotonfile/photonfile.py#L412) should be outside the for-loop - in the current state always a layer with only one sublayer is created.

**Comment by fookatchu** [comment]
Correct, thanks for pointing that out. I will write a fix it at the weekend.

**Comment by Raukk** [comment]
Wow, I literally just came here to submit a pull request for this bug, and I was very confused when it wasn't there (I found the bug last night).
Lol, what are the chances that you'd fix the issue 2 hours before I went to submit it.

**Comment by fookatchu** [comment]
Sorry for that :). Any help is gratefully accepted. If you find any other bugs or improvements, just let me know!

**Comment by Raukk** [comment]
> Sorry for that :). Any help is gratefully accepted. If you find any other bugs or improvements, just let me know!

No problem, I just found the timing very funny.

This bug reminds my of why I hate Python (and why { } are so nice)

I'll be sure to let you know if I run into any bugs, or feature requests.
